### ISSUE TITLE
compilation

### ISSUE THREAD

**Issue by mwtsai** [APCLab/bitcoin#6]
關於compilation的問題，我現在是使用windows系統，
windows要編譯的方法有兩種
1. Cross -compilation from Ubuntu
2. Building on Windows itself

由於我個人對於linux不太熟，因此使用第2種方法，但build-windows.md也只有教學第一種作法。
網路上資料就找到這篇算是比較清楚的，因此使用這篇來建建看，是使用MinGW的。

@iblis17 覺得現階段用1會比較好嗎，還是說直接用unix系統呢？

**Comment by iblislin** [comment]
我的建議是： 先去看看 unix 吧， 206 有 ubuntu
- 我不知到你對這塊的知識有多少，但是我先講一下這些怪物的等級。
  1. Level 1: compile on unix 是最簡單，而且網絡上相關資源最多的，這是比較容易的。因為 unix 本來就是常常幫開發者準備好東西了。
  2. Level 2: cross-compile 如果你沒有 level 1 的知識，那麼你在越級打怪
  3. Level 99: 在 windows 上 compile 東西，這 ... 不是開玩笑， 你要具備前面 比 level 1 更多的知識，而且還附帶 windows 的 domain knowledge ，這個系統上沒有準備好給開發者的相關工具，統統自己準備。而且理論上如果你的知識夠，這塊不需要給文件，理論上看著 unix 的文件你就可以達成在 windows compile。這是越級打 boss。

**Comment by iblislin** [comment]
@mwtsai 那麼選一個吧。

方向確定了就開始做，有問題就問。

**Comment by iblislin** [comment]
~~沒人說不可以越級打 boss，看看 C8763~~

**Comment by mwtsai** [comment]
謝謝你的建議跟介紹，我會先看build-unix.md

**Comment by mwtsai** [comment]
已經compile完了喔，有錢包跑出來，以下是執行檔跑出來的東西

arayaneko@doric:~/bitcoin-0.12.1/src$ ./bitcoin-cli
Bitcoin Core RPC client version v0.12.1.0-g9779e1e

Usage:
  bitcoin-cli [options] <command> [params]  Send command to Bitcoin Core
  bitcoin-cli [options] help                List commands
  bitcoin-cli [options] help <command>      Get help for a command

Options:

  -?
       This help message

  -conf=<file>
       Specify configuration file (default: bitcoin.conf)

  -datadir=<dir>
       Specify data directory

Chain selection options:

  -testnet
       Use the test chain

  -regtest
       Enter regression test mode, which uses a special chain in which blocks
       can be solved instantly. This is intended for regression testing tools
       and app development.

  -rpcconnect=<ip>
       Send commands to node running on <ip> (default: 127.0.0.1)

  -rpcport=<port>
       Connect to JSON-RPC on <port> (default: 8332 or testnet: 18332)

  -rpcwait
       Wait for RPC server to start

  -rpcuser=<user>
       Username for JSON-RPC connections

  -rpcpassword=<pw>
       Password for JSON-RPC connections

  -rpcclienttimeout=<n>
       Timeout during HTTP requests (default: 900)

arayaneko@doric:~/bitcoin-0.12.1/src$ ./bitcoind
^Carayaneko@doric:~/bitcoin-0.12.1/src$ cd qt
arayaneko@doric:~/bitcoin-0.12.1/src/qt$ ./bitcoin-qt

**Comment by iblislin** [comment]
@mwtsai looks fine!
